"""Persistence boundary for conversation state."""

from __future__ import annotations

from typing import Protocol

from qaneris.conversation.models import Conversation, Message, SemanticMemory


class ConversationRepository(Protocol):
    def create(self, conversation: Conversation) -> Conversation: ...
    def get(self, conversation_id: str) -> Conversation: ...
    def list(self, workspace_id: str) -> list[Conversation]: ...
    def add_message(self, message: Message) -> None: ...
    def messages(self, conversation_id: str, limit: int | None = None) -> list[Message]: ...
    def memory(self, conversation_id: str) -> SemanticMemory: ...
    def memory_revision(self, conversation_id: str) -> int: ...
    def put_memory(
        self, conversation_id: str, memory: SemanticMemory, expected_revision: int
    ) -> None: ...
