"""Persistence and scheduling boundaries for runs."""

from collections.abc import Callable
from typing import Protocol

from smartdata.runtime.models import Run, RunEvent


class RunRepository(Protocol):
    def create(self, run: Run) -> Run: ...
    def get(self, run_id: str) -> Run: ...
    def save(self, run: Run, expected_revision: int) -> Run: ...
    def append_event(self, run_id: str, event_type: str, payload: dict) -> RunEvent: ...
    def events(self, run_id: str, after_sequence: int = 0) -> list[RunEvent]: ...
    def last_event(self, run_id: str) -> RunEvent | None: ...
    def recover_interrupted(self) -> None: ...
    def queued_run_ids(self) -> list[str]: ...
    def incomplete_completions(self) -> list[Run]: ...
    def incomplete_clarifications(self) -> list[Run]: ...


class RunScheduler(Protocol):
    def submit(self, run_id: str, work: Callable[[str], None]) -> None: ...
